Reset accounts
Manta-Network/manta-signer pull request #121
Opened 2022-06-27 15:30 UTC by tommyjk21

Adds a menu item allowing the user to reset their account. closes #29

---

Before we can merge this PR, please make sure that all the following items have been checked off:

- [ ] Linked to an issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Added **one** line describing your change in [`CHANGELOG.md`](https://github.com/manta-network/manta-signer/blob/main/CHANGELOG.md) and added the appropriate `changelog` label to the PR.
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer.

2022-06-30 17:39 UTC, Kevingislason commented on Cargo.toml
> +manta-util = { git = "https://github.com/manta-network/manta-rs", branch = "fix/reduce-key-rederivations", default-features = false }
I think you can use `tag = "v0.5.1"` instead of specifying branch now

2022-07-04 21:26 UTC, Kevingislason requested changes
When the user clicks "Reset account", or when the user opens the app without a seed, I think they should get the option to either recover from mnemonic or restart from a fresh seed. So I think we need one more page with two buttons--"New account" and "Recover account", which direct the user to the appropriate page. This page could also include a warning--as it stands, users might accidentally delete their accounts on a misclick.

edit based on discussion in full stack meeting:
we can do "Reset account" in the upper menu bar--we don't need to do this now, can do this in a separate PR. We still want to include a warning before allowing the user to reset their account.

2022-07-04 21:26 UTC, Kevingislason commented on ui/src-tauri/src/main.rs
> +                    .add_item(CustomMenuItem::new("reset", "Reset Seed"))
"Reset Account" is a little more obvious imo

2022-07-04 21:26 UTC, Kevingislason commented on ui/src/pages/ResetAccount.js
> +              <Form.TextArea onChange={onEnterSeedPhrase}>
for some reason I can't copy-paste into this text area

2022-07-04 21:26 UTC, Kevingislason commented on ui/src/pages/ResetAccount.js
> +          {!validSeedPhrase && <Label basic color='yellow'>Enter a valid seed phrase</Label> }
I don't think this should display if the user hasn't typed in anything yet

2022-07-05 17:21 UTC, Kevingislason commented on ui/src-tauri/src/main.rs
> +                    .add_item(CustomMenuItem::new("reset", "Reset Seed"))
Actually "Recover from seed" is best

2022-07-07 00:14 UTC, bhgomes requested changes

2022-07-07 00:14 UTC, bhgomes commented on src/service.rs
> +    ChannelClosedError,
```suggestion
    /// Reset Channel Closed Error
    ResetChannelClosedError,
```

2022-07-07 00:14 UTC, bhgomes commented on src/secret.rs
> +pub type ResetInfo = (SecretString, SecretString);
Make this a struct

2022-07-07 00:14 UTC, bhgomes commented on examples/test_server.rs
> +    service::start(config, MockUser::new(&mut OsRng), rx).await
```suggestion
    service::start(config, MockUser::new(&mut OsRng), None).await
```

2022-07-07 00:14 UTC, bhgomes commented on src/service.rs
> +pub async fn start<A>(config: Config, authorizer: A, reset_rx: Receiver<ResetInfo>) -> Result<()>
```suggestion
pub async fn start<A>(config: Config, authorizer: A, reset_receiver: Option<Receiver<ResetInfo>>) -> Result<()>
```

2022-07-07 00:14 UTC, bhgomes commented on src/service.rs
> +pub async fn start<A>(config: Config, authorizer: A, reset_rx: Receiver<ResetInfo>) -> Result<()>
And add documentation about this optional handler.

2022-07-07 00:14 UTC, bhgomes commented on src/service.rs
> +
Move this into its own function and use full names for all variables.

2022-07-07 00:14 UTC, bhgomes commented on src/service.rs
> +            std::mem::swap(&mut *state_handle.lock(), &mut new_state);
Don't use `std` when the same function exists in `core`. Always prefer this ordering: `core` -> `alloc` -> `std`.

2022-07-07 00:14 UTC, bhgomes commented on src/service.rs
> +    }
```suggestion
    /// Returns a handle to the state of the server.
    #[inline]
    pub fn state(&self) -> Arc<Mutex<State>> {
        self.state.clone()
    }
```

2022-07-07 00:14 UTC, bhgomes commented on src/service.rs
> +async fn do_reset(mnemonic: SecretString, password: SecretString, config: &Config) -> State {
Always prefer non-transient arguments first: 

```suggestion
async fn reset_state(config: &Config, mnemonic: SecretString, password: SecretString) -> State {
```

2022-07-07 00:14 UTC, bhgomes commented on src/service.rs
> +    }
```suggestion
    State {
        config: config.clone(),
        signer: Signer::from_parts(parameters, state),
    }
```

2022-07-07 00:14 UTC, bhgomes commented on src/service.rs
> +async fn do_reset(mnemonic: SecretString, password: SecretString, config: &Config) -> State {
Please use proper error handling for this function. Don't just expect on all the errors, pass them up to the caller.

2022-07-07 00:14 UTC, bhgomes commented on src/service.rs
> +        .expect("Could not save signer state.");
Much of this code is repeated in other parts of `service.rs`. Please find a refactoring that does not introduce repetition (even if that means writing new functions that generalize over all the use cases).

2022-07-07 00:14 UTC, bhgomes commented on ui/src-tauri/src/main.rs
> +    Ok(true)
Add a `from_strings` (bikeshed the name) method to the `ResetInfo` struct that takes `Strings` and converts them into `Secret`s. Also, return the error back up to the caller.

```suggestion
    reset_handle.send(ResetInfo::from_strings(phrase, password)).await
```

2022-07-07 00:14 UTC, bhgomes commented on ui/src-tauri/src/main.rs
> +    let (reset_tx, reset_rx) = channel(1);
```suggestion
    let (reset_sender, reset_receiver) = channel(1);
```

2022-07-07 00:14 UTC, bhgomes commented on ui/src-tauri/src/main.rs
> +                        window.emit("reset", "").unwrap();
```suggestion
                        app.get_window("main").unwrap().emit("reset", "").unwrap();
```

2022-07-07 00:14 UTC, bhgomes commented on ui/src-tauri/src/main.rs
> +                service::start(config, User::new(window, password, retry), reset_rx)
```suggestion
                service::start(config, User::new(window, password, retry), Some(reset_receiver))
```

2022-07-07 00:14 UTC, bhgomes commented on ui/src-tauri/src/main.rs
> +        .manage(reset_tx)
```suggestion
        .manage(reset_sender)
```

2022-07-07 00:14 UTC, bhgomes commented on ui/src/App.js
> +    console.log("[INFO]: Send info to signer server.");
```suggestion
    console.log("[INFO]: Send reset info to signer server.");
```

2022-10-06 09:24 UTC, closed without merging