upgrade proving keys and manta-rs for release
Manta-Network/manta-signer pull request #262
Opened 2023-01-23 21:29 UTC by Apokalip

Signed-off-by: Apokalip <simeon@manta.network>

---

Before we can merge this PR, please make sure that all the following items have been checked off:

- [ ] Linked to an issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Added **one** line describing your change in [`CHANGELOG.md`](https://github.com/manta-network/manta-signer/blob/main/CHANGELOG.md) and added the appropriate `changelog` label to the PR.
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer.

2023-01-23 21:41 UTC, Kevingislason approved these changes

2023-01-23 21:52 UTC, Kevingislason requested changes
err sorry, missing two things:

- Need to update changelog
- Need to bump version numbers in `ui/src-tauri/tauri.conf.json` and `ui/public/about.html`

2023-01-23 21:55 UTC, Kevingislason commented
Also, I think this should be 1.1.0 since it requires a coordinated front end update

2023-01-24 12:59 UTC, Apokalip commented
> Also, I think this should be 1.1.0 since it requires a coordinated front end update
> 
> edit: actually, forget this, I think this release will work with the current front end. We should bump minimum supported signer version on front end, but only due to runtime changes, not due to signer changes.

I mean we are bug fixing and we are not changing protocols or doing any large feature changes related to front end, shouldnt it just be v1.0.1, If its a big feature and changes we iterate the second number and large changes/refactors change the first number?

2023-01-24 14:46 UTC, bhgomes approved these changes

2023-01-24 15:05 UTC, merged