Add js libs
Manta-Network/manta-signer pull request #52
Opened 2022-02-02 23:22 UTC by Kevingislason

## Description

Duplicate of https://github.com/Manta-Network/manta-signer/pull/50
That branch seems to be breaking CI builds for no reason, so trying to see if a fresh branch helps, idk

closes: #XXXX

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Test following procedure in docs/testing-workflow.md
- [ ] Updated relevant documentation in the code.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Update the version numbers properly:
   * Cargo.toml
   * ui/src-tauri/Cargo.toml
   * ui/src-tauri/tauri.conf.json
   * ui/public/about.html
   * ui/package.json

2022-02-04 17:37 UTC, tjsharp1 approved these changes
:+1:

2022-02-04 21:56 UTC, bhgomes requested changes

2022-02-04 21:56 UTC, bhgomes commented on js/e2e/simulation/src/main.rs
> +                    if asset.value > 0 {
If we got rid of the zero value in the simulation, we can remove this check.

2022-02-08 17:41 UTC, bhgomes approved these changes

2022-02-09 20:25 UTC, merged